on:
  push:
    branches:
      - 'master'
jobs:
    test:
      name: Run
      runs-on: ubuntu-latest
      steps:
        - shell: bash
          env: # Set the secret as an input
            MY_SECRET: ${{ secrets.WOW_NICE }}
          run: |
            echo $MY_SECRET
