on:
  push:
    branches:
      - 'master'
jobs:
    test:
      name: Run
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Run
          run: |
            echo ${{ secrets.BEAMMP_SECRET_SENTRY_URL }}
