on:
  push:
    branches:
      - 'master'
jobs:
    test:
      name: Run
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Run
          with: # Set the secret as an input
            MY_SECRET: ${{ secrets.BEAMMP_SECRET_SENTRY_URL }}
          run: |
            echo $MY_SECRET
