on:
  push:
    branches:
      - 'master'
jobs:
    test:
      name: Run
      runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Run
        env: # Or as an environment variable
          BEAMMP_SECRET_SENTRY_URL: ${{ secrets.BEAMMP_SECRET_SENTRY_URL }}
        run: |
          echo BEAMMP_SECRET_SENTRY_URL
